package com.example.groupprojectapp.timeline.ui

import com.example.groupprojectapp.tasks.data.TaskStatus

/**
 * MODEL (MVVM) — UI display model, not a Room entity:
 * one bar on the timeline, already converted from a Task into numbers the
 * screen can draw directly.
 *
 * Built by [TimelineViewModel] from TaskWithAssignee. The VIEW never sees
 * raw dates: it only multiplies startOffsetDays / lengthDays by its own
 * width per day.
 *
 * taskId is kept so a bar can later open that task's documentation (A5).
 */
data class TimelineItem(
    val taskId: Long,  // taskId should already be generated by the Database
    val title: String = "Unnamed Task",
    val assigneeName: String = "Unassigned",
    val status: TaskStatus = TaskStatus.TODO,
    val startOffsetDays: Int = 0, // the days from the timeline's first day to where the bar begins
    val lengthDays: Int = 1, // how many days the bar is
    val isOverdue: Boolean = false // for colour status
)

// other notes: (TODO REMOVE THIS BEFORE SUBMISSION)
/*
   startOffsetDays -> position where the bar begins
      how far from the left edge of the whole chart does the bar start?
      need chart's start date and chart's first date (difference between them)

    lengthDays -> width - how long the bar is
    how many days does this task last?
      need task's start date and due date (dif between two + 1)
*/