package com.example.groupprojectapp.timeline.data

import com.example.groupprojectapp.tasks.data.TaskStatus

data class TimelineItem(
    val taskId: Long,  // taskId should already be generated by the Database
    val title: String = "Unnamed Task",
    val assigneeName: String = "Unassigned",
    val status: TaskStatus = TaskStatus.TODO,
    val startOffsetDays: Int = 0, // the days from the timeline's first day to where the bar begins
    val lengthDays: Int = 1, // how many days the bar is
)